export const CarsList = [
    {
        id: 1,
        src: '/src/mini-games/nfs/img/M5CS.png',
        poster: '/src/mini-games/nfs/img/posters/BMW-M5-CS.png',
        carName: 'Bmw m5 cs',
        maxSpeed: 331,
        accelInGame: 45,
        breakingInGame: -150,
        decelInGame: -18,
        manageability: 80,
        braking: 85,
        dynamics: 89,
        width: 110,
        height: 103,
    },
    {
        id: 2,
        src: '/src/mini-games/nfs/img/hero.png',
        poster: '/src/mini-games/nfs/img/posters/ferrari-testerossa.png',
        carName: 'Ferrari testerossa',
        maxSpeed: 200,
        accelInGame: 38,
        breakingInGame: -80,
        decelInGame: -14,
        manageability: 51,
        braking: 39,
        dynamics: 30,
        width: 110,
        height: 56,
    },
];